---
title: "Gene Dosage Effects of Chromosome 12 Trisomy in Human Induced Pluripotent Stem Cells (iPSCs)"
author: "Fahmida Sultana"
date: 2025-07-28
format: html
execute:
  echo: true

---
#Project Overview
Aneuploidy, the presence of an abnormal number of chromosomes, is a common genomic alteration observed in both developmental disorders and cancer. While most aneuploidies are detrimental to cellular function, some specific chromosomal gains may confer selective growth advantages in certain contexts. Human induced pluripotent stem cells (iPSCs) serve as a powerful model system to study the effects of aneuploidy due to their self-renewal capacity and potential for differentiation.

In this project, we focus on trisomy of chromosome 12 (T12), a frequently observed aneuploidy in cultured iPSCs. This chromosomal gain is particularly intriguing because it has been associated with increased proliferation and stemness, and is often detected in iPSC lines during long-term culture. By investigating transcriptomic data, we aim to explore how the extra copy of chromosome 12 alters gene expressions, and how these molecular changes contribute to altered cellular phenotypes.

Understanding the gene dosage effects of trisomy 12 in iPSCs not only provides insights into the biology of stem cell maintenance and genomic instability but also has implications for regenerative medicine and disease modeling, where genomic integrity is crucial.

```

```{r}

```

