project:
  type: website

website:
  title: "Fahmida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: styles.scss
    mainfont: Jost
    toc: true
    toc-depth: 3
    number-sections: true
    



